---
# Default variables for monitoring role
# All variables prefixed with monitoring_ per ansible-lint convention

monitoring_node_exporter_version: "1.7.0"
monitoring_node_exporter_port: 9100

monitoring_prometheus_version: "2.48.0"
monitoring_prometheus_port: 9090
monitoring_prometheus_scrape_interval: 15s

monitoring_install_prometheus: false
