---
# Install Prometheus

- name: Check if Prometheus is installed
  ansible.builtin.stat:
    path: /usr/local/bin/prometheus
  register: monitoring_prometheus_installed

- name: Download Prometheus
  ansible.builtin.get_url:
    url: >-
      https://github.com/prometheus/prometheus/releases/download/v{{
      monitoring_prometheus_version }}/prometheus-{{
      monitoring_prometheus_version }}.linux-amd64.tar.gz
    dest: "/tmp/prometheus-{{ monitoring_prometheus_version }}.linux-amd64.tar.gz"
    mode: '0644'
  when: not monitoring_prometheus_installed.stat.exists

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ monitoring_prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
  when: not monitoring_prometheus_installed.stat.exists

- name: Install Prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ monitoring_prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  loop:
    - prometheus
    - promtool
  when: not monitoring_prometheus_installed.stat.exists
  notify: Restart prometheus

- name: Configure Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart prometheus

- name: Create Prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart prometheus

- name: Enable and start Prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
